leave-venv: attempt to bypass broken/nonexistent pyenv installations

diff --git a/bin/leave-venv b/bin/leave-venv
--- a/bin/leave-venv
+++ b/bin/leave-venv
@@ -8,6 +8,21 @@ if [ -z "$prog" ]; then
     echo "usage: $0 PROGRAM" >&2
     exit 1
 fi
-export PATH="$HOME/bin:$HOME/.pyenv/shims:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
+
+new_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
+
+pyenv_shims="${PYENV_ROOT:-$HOME/.pyenv}/shims"
+if [[ -f "$pyenv_shims/$prog" ]]; then
+    if "$pyenv_shims/$prog" --version &>/dev/null; then
+        new_path="$pyenv_shims:$new_path"
+    else
+        echo >&2 "WARNING: leave-venv: pyenv detected but unable to invoke: $pyenv_shims/$prog --version"
+        echo >&2 "WARNING: leave-venv: falling back to non-pyenv"
+    fi
+fi
+
+new_path="$HOME/bin:$new_path"
+
+export PATH="$new_path"
 export PYTHONPATH=
 "$prog" "$@"
